#!/usr/bin/env python3
"""Generate data/load_data.cypher for the Jurisprudence discount-decision demo.

Deterministic seed data:
- 18 customers (Standard/Gold/VIP), cosmetics orders, incidents over ~6 months
- 6 policies covering the common incident types + 1 "Policy Gap" placeholder
- 2 pre-seeded precedents (unrelated incident types, past dates)
- The scripted Case 1 / Case 2 / Case 3 records with FIXED ids:
    Case 1: INC-001  Gold customer, damaged_in_transit          -> matches POL-005
    Case 2: INC-101  Standard,     packaging_damaged_product_usable -> no policy, escalate
    Case 3: INC-102  Standard,     packaging_damaged_product_usable -> cites Case-2 precedent

Dates are generated relative to today so recency windows keep working at
rehearsal time and on demo day. Filler data uses a fixed random seed.
"""

import random
from datetime import date, timedelta

random.seed(42)
TODAY = date.today()


def d(days_ago: int) -> str:
    return (TODAY - timedelta(days=days_ago)).isoformat()


def esc(s: str) -> str:
    return s.replace("'", "\\'")


# ---------------------------------------------------------------------------
# Catalog of cosmetics products (name, unit price EUR)
# ---------------------------------------------------------------------------
CATALOG = [
    ("SKU-SER-001", "Revitalift Filler Serum 30ml", 32.90),
    ("SKU-SER-002", "Hyaluron Expert Night Serum 30ml", 27.50),
    ("SKU-SER-003", "Vitamin C Brightening Serum 20ml", 24.90),
    ("SKU-CRM-001", "Age Perfect Day Cream 50ml", 21.90),
    ("SKU-CRM-002", "Hydra Genius Water Cream 70ml", 18.50),
    ("SKU-CRM-003", "Collagen Re-Plumper Night Cream 50ml", 19.90),
    ("SKU-LIP-001", "Color Riche Satin Lipstick — Rouge 357", 13.90),
    ("SKU-LIP-002", "Infallible Matte Resistance Lipstick", 14.50),
    ("SKU-FRG-001", "La Vie Est Belle EDP 50ml", 89.00),
    ("SKU-FRG-002", "Libre Intense EDP 30ml", 72.00),
    ("SKU-MSK-001", "Pure Clay Detox Mask 50ml", 12.90),
    ("SKU-SHM-001", "Elvive Bond Repair Shampoo 200ml", 9.90),
    ("SKU-FND-001", "True Match Foundation 30ml — 3N", 15.90),
    ("SKU-EYE-001", "Lash Paradise Mascara — Black", 13.50),
]

FIRST = ["Camille", "Léa", "Nina", "Chloé", "Manon", "Sofia", "Inès", "Jade",
         "Louise", "Emma", "Julien", "Karim", "Thomas", "Nadia", "Elodie",
         "Marc", "Amira", "Pauline"]
LAST = ["Laurent", "Moreau", "Rousseau", "Dubois", "Lefèvre", "Garcia",
        "Bennani", "Martin", "Petit", "Fontaine", "Chevalier", "Da Silva",
        "Nguyen", "Kessler", "Marechal", "Blanc", "Haddad", "Roux"]

# Incident types covered by written policies
COVERED_TYPES = [
    ("damaged_in_transit", "Order arrived damaged in transit"),
    ("wrong_item_shipped", "A different product was shipped"),
    ("late_delivery", "Delivery arrived after the promised date"),
    ("quality_complaint", "Product quality below expectations"),
]

# ---------------------------------------------------------------------------
# Build statements
# ---------------------------------------------------------------------------
stmts: list[str] = []

stmts.append("// ============================================================\n"
             "// Jurisprudence demo — generated by generate_data.py\n"
             "// Step 0: Clean database\n"
             "// ============================================================\n"
             "MATCH (n) DETACH DELETE n")

# Constraints & indexes
for label in ["Customer", "Order", "Incident", "Policy", "Case", "Human", "Precedent"]:
    stmts.append(
        f"CREATE CONSTRAINT {label.lower()}_id IF NOT EXISTS "
        f"FOR (n:{label}) REQUIRE n.id IS UNIQUE"
    )
stmts.append("CREATE INDEX incident_type IF NOT EXISTS FOR (n:Incident) ON (n.type)")
stmts.append("CREATE INDEX policy_incident_type IF NOT EXISTS FOR (n:Policy) ON (n.incident_type)")
stmts.append("CREATE INDEX precedent_incident_type IF NOT EXISTS FOR (n:Precedent) ON (n.incident_type)")

# ---------------------------------------------------------------------------
# Policies (conditions are plain properties — one WHERE clause, no Condition nodes)
# ---------------------------------------------------------------------------
POLICIES = [
    # (id, name, incident_type, min_tier, max_recency_days, action, discount_pct, description)
    ("POL-001", "Transit Damage — Standard Care", "damaged_in_transit", "Standard", 60,
     "refund_or_replacement_plus_discount", 15,
     "Product damaged in transit: offer replacement or refund plus a 15% goodwill discount on the next order."),
    ("POL-002", "Transit Damage — Premium Care", "damaged_in_transit", "Gold", 60,
     "express_replacement_plus_discount", 20,
     "Gold and VIP customers with transit damage get an express replacement and a 20% discount on the current order."),
    ("POL-003", "Wrong Item Shipped", "wrong_item_shipped", "Standard", 45,
     "replacement_plus_apology_discount", 10,
     "Wrong item shipped: send the correct item with prepaid return label and a 10% apology discount."),
    ("POL-004", "Late Delivery Credit", "late_delivery", "Standard", 30,
     "shipping_credit", 10,
     "Delivery later than promised: refund shipping fees and issue a 10% credit voucher."),
    ("POL-005", "Quality Complaint Refund", "quality_complaint", "Standard", 90,
     "refund_after_review", 0,
     "Substantiated quality complaints are refunded in full after a quality-team review. No discount."),
    ("POL-006", "VIP White Glove", "quality_complaint", "VIP", 90,
     "refund_plus_discount", 25,
     "VIP quality complaints: immediate refund, no review required, 25% discount on the next order."),
]

for pid, name, itype, tier, days, action, pct, desc in POLICIES:
    stmts.append(
        f"MERGE (p:Policy {{id: '{pid}'}})\n"
        f"SET p.name = '{esc(name)}', p.incident_type = '{itype}', p.min_tier = '{tier}',\n"
        f"    p.max_recency_days = {days}, p.action = '{action}', p.discount_pct = {pct},\n"
        f"    p.description = '{esc(desc)}', p.source = 'customer_care_handbook_v7'"
    )

# The placeholder every live precedent refines: represents the coverage gap.
stmts.append(
    "MERGE (p:Policy {id: 'POL-GAP'})\n"
    "SET p.name = 'Policy Gap — uncovered incident types', p.incident_type = 'uncovered',\n"
    "    p.min_tier = 'Standard', p.max_recency_days = null, p.action = 'escalate_to_human',\n"
    "    p.discount_pct = null,\n"
    "    p.description = 'Placeholder policy: incidents that no written policy covers. Precedents that fill the gap REFINE this node until the handbook is updated.',\n"
    "    p.source = 'system'"
)

# ---------------------------------------------------------------------------
# Humans (customer care leads)
# ---------------------------------------------------------------------------
HUMANS = [
    ("HUM-001", "Sophie Marchand", "Customer Care Lead"),
    ("HUM-002", "Karim Benali", "Senior CS Manager"),
]
for hid, name, role in HUMANS:
    stmts.append(
        f"MERGE (h:Human {{id: '{hid}'}}) SET h.name = '{esc(name)}', h.role = '{esc(role)}'"
    )

# ---------------------------------------------------------------------------
# Scripted customers for the 3 cases (fixed ids)
# ---------------------------------------------------------------------------
def customer(cid, name, tier):
    return (f"MERGE (c:Customer {{id: '{cid}'}}) "
            f"SET c.name = '{esc(name)}', c.tier = '{tier}'")


def order(cid, oid, sku, pname, amount, days_ago):
    return (
        f"MATCH (c:Customer {{id: '{cid}'}})\n"
        f"MERGE (o:Order {{id: '{oid}'}})\n"
        f"SET o.sku = '{sku}', o.product_name = '{esc(pname)}', o.amount = {amount}, o.date = date('{d(days_ago)}')\n"
        f"MERGE (c)-[:HAD]->(o)"
    )


def incident(oid, iid, itype, desc, days_ago, status="open"):
    return (
        f"MATCH (o:Order {{id: '{oid}'}})\n"
        f"MERGE (i:Incident {{id: '{iid}'}})\n"
        f"SET i.type = '{itype}', i.description = '{esc(desc)}', "
        f"i.reported_at = date('{d(days_ago)}'), i.status = '{status}'\n"
        f"MERGE (o)-[:AFFECTED_BY]->(i)"
    )


stmts.append("// ── Scripted Case 1 / 2 / 3 records (fixed ids) ──────────────")

# Case 1 — Gold customer, damaged in transit -> POL-002 auto-approval
stmts.append(customer("CUST-001", "Camille Laurent", "Gold"))
stmts.append(order("CUST-001", "ORD-001", "SKU-FRG-001", "La Vie Est Belle EDP 50ml", 89.00, 3))
stmts.append(incident("ORD-001", "INC-001", "damaged_in_transit",
                      "Parcel crushed during delivery; fragrance bottle cracked, product unusable.", 2))

# Case 2 — Standard customer, packaging damaged but product fine -> no policy
stmts.append(customer("CUST-002", "Léa Moreau", "Standard"))
stmts.append(order("CUST-002", "ORD-002", "SKU-SER-001", "Revitalift Filler Serum 30ml", 32.90, 5))
stmts.append(incident("ORD-002", "INC-101", "packaging_damaged_product_usable",
                      "Outer carton and pump cap dented, cellophane torn — the serum itself is intact and fully usable.", 2))

# Case 3 — another Standard customer, same uncovered incident type
stmts.append(customer("CUST-003", "Nina Rousseau", "Standard"))
stmts.append(order("CUST-003", "ORD-003", "SKU-CRM-001", "Age Perfect Day Cream 50ml", 21.90, 2))
stmts.append(incident("ORD-003", "INC-102", "packaging_damaged_product_usable",
                      "Jar sleeve scuffed and box corner crushed in the mail; cream sealed and undamaged.", 1))

# ---------------------------------------------------------------------------
# Pre-seeded precedents: unrelated incident types, past dates, with their
# original (resolved) incidents and cases so the graph tells a full story.
# ---------------------------------------------------------------------------
stmts.append("// ── Pre-seeded precedents (unrelated types, past dates) ──────")

stmts.append(customer("CUST-004", "Chloé Dubois", "Gold"))
stmts.append(order("CUST-004", "ORD-004", "SKU-LIP-001", "Color Riche Satin Lipstick — Rouge 357", 13.90, 95))
stmts.append(incident("ORD-004", "INC-201", "gift_missing_from_set",
                      "Holiday coffret arrived without the advertised travel-size mascara.", 93, status="resolved"))
stmts.append(
    "MATCH (i:Incident {id: 'INC-201'}), (h:Human {id: 'HUM-001'}), (gap:Policy {id: 'POL-GAP'})\n"
    "MERGE (cs:Case {id: 'CASE-201'}) SET cs.opened_at = date('" + d(93) + "'), cs.status = 'resolved_by_human'\n"
    "MERGE (cs)-[:CONCERNS]->(i)\n"
    "MERGE (cs)-[:DECIDED_BY]->(h)\n"
    "MERGE (pr:Precedent {id: 'PR-001'})\n"
    "SET pr.established_at = date('" + d(93) + "'), pr.incident_type = 'gift_missing_from_set',\n"
    "    pr.min_tier = 'Standard', pr.action = 'ship_missing_item_plus_discount', pr.discount_pct = 5,\n"
    "    pr.rationale = 'Missing gift-with-purchase: ship the missing item and apply a 5% goodwill discount. No refund of the set.'\n"
    "MERGE (h)-[:ESTABLISHES]->(pr)\n"
    "MERGE (pr)-[:REFINES]->(gap)\n"
    "SET i.resolution_type = 'human', i.resolution_ref = 'PR-001',\n"
    "    i.resolution_action = 'ship_missing_item_plus_discount', i.resolution_discount_pct = 5,\n"
    "    i.resolved_at = date('" + d(93) + "')"
)

stmts.append(customer("CUST-005", "Manon Lefèvre", "Standard"))
stmts.append(order("CUST-005", "ORD-005", "SKU-FRG-002", "Libre Intense EDP 30ml", 72.00, 71))
stmts.append(incident("ORD-005", "INC-202", "fragrance_leaked_half_empty",
                      "Fragrance arrived sealed but bottle only half full — leaked inside packaging.", 70, status="resolved"))
stmts.append(
    "MATCH (i:Incident {id: 'INC-202'}), (h:Human {id: 'HUM-002'}), (gap:Policy {id: 'POL-GAP'})\n"
    "MERGE (cs:Case {id: 'CASE-202'}) SET cs.opened_at = date('" + d(70) + "'), cs.status = 'resolved_by_human'\n"
    "MERGE (cs)-[:CONCERNS]->(i)\n"
    "MERGE (cs)-[:DECIDED_BY]->(h)\n"
    "MERGE (pr:Precedent {id: 'PR-002'})\n"
    "SET pr.established_at = date('" + d(70) + "'), pr.incident_type = 'fragrance_leaked_half_empty',\n"
    "    pr.min_tier = 'Standard', pr.action = 'replacement_no_return', pr.discount_pct = 0,\n"
    "    pr.rationale = 'Leaked fragrance: full replacement, customer keeps the leaked bottle. No discount on top.'\n"
    "MERGE (h)-[:ESTABLISHES]->(pr)\n"
    "MERGE (pr)-[:REFINES]->(gap)\n"
    "SET i.resolution_type = 'human', i.resolution_ref = 'PR-002',\n"
    "    i.resolution_action = 'replacement_no_return', i.resolution_discount_pct = 0,\n"
    "    i.resolved_at = date('" + d(70) + "')"
)

# ---------------------------------------------------------------------------
# Filler customers / orders / incidents (covered types only, mostly resolved)
# ---------------------------------------------------------------------------
stmts.append("// ── Filler population (covered incident types only) ──────────")

TIERS = ["Standard", "Standard", "Standard", "Gold", "Gold", "VIP"]
used_names = {"Camille Laurent", "Léa Moreau", "Nina Rousseau", "Chloé Dubois", "Manon Lefèvre"}
order_seq = 100
incident_seq = 300

for n in range(6, 19):  # CUST-006 .. CUST-018
    cid = f"CUST-{n:03d}"
    while True:
        name = f"{random.choice(FIRST)} {random.choice(LAST)}"
        if name not in used_names:
            used_names.add(name)
            break
    tier = random.choice(TIERS)
    stmts.append(customer(cid, name, tier))

    for _ in range(random.randint(2, 3)):
        order_seq += 1
        oid = f"ORD-{order_seq}"
        sku, pname, price = random.choice(CATALOG)
        days_ago = random.randint(5, 180)
        stmts.append(order(cid, oid, sku, pname, price, days_ago))

        # ~65% of orders had an incident
        if random.random() < 0.65:
            incident_seq += 1
            iid = f"INC-{incident_seq}"
            itype, base_desc = random.choice(COVERED_TYPES)
            reported = max(days_ago - random.randint(1, 4), 1)
            # older incidents are resolved by their policy; recent ones stay open
            if reported > 20:
                pol = {"damaged_in_transit": "POL-001", "wrong_item_shipped": "POL-003",
                       "late_delivery": "POL-004", "quality_complaint": "POL-005"}[itype]
                pct = {"POL-001": 15, "POL-003": 10, "POL-004": 10, "POL-005": 0}[pol]
                stmts.append(incident(oid, iid, itype, base_desc + ".", reported, status="resolved"))
                stmts.append(
                    f"MATCH (i:Incident {{id: '{iid}'}})\n"
                    f"SET i.resolution_type = 'policy', i.resolution_ref = '{pol}',\n"
                    f"    i.resolution_action = 'per_policy', i.resolution_discount_pct = {pct},\n"
                    f"    i.resolved_at = date('{d(max(reported - 1, 0))}')"
                )
            else:
                stmts.append(incident(oid, iid, itype, base_desc + ".", reported, status="open"))

# A couple of deterministic OPEN incidents on covered types, so the Decide
# tab has live material beyond the 3 scripted cases.
stmts.append(customer("CUST-019", "Louise Fontaine", "VIP"))
stmts.append(order("CUST-019", "ORD-090", "SKU-SER-003", "Vitamin C Brightening Serum 20ml", 24.90, 6))
stmts.append(incident("ORD-090", "INC-401", "late_delivery",
                      "Express order promised in 48h, delivered after 6 days.", 4))
stmts.append(customer("CUST-020", "Marc Chevalier", "Standard"))
stmts.append(order("CUST-020", "ORD-091", "SKU-MSK-001", "Pure Clay Detox Mask 50ml", 12.90, 8))
stmts.append(incident("ORD-091", "INC-402", "wrong_item_shipped",
                      "Ordered the detox mask, received a glow mask instead.", 5))

out = ";\n\n".join(stmts) + ";\n"

with open("data/load_data.cypher", "w") as f:
    f.write(out)

print(f"Wrote data/load_data.cypher ({len(stmts)} statements)")
